---
title: "Independent Project"
author: "Rui Lu"
date: "2020/12/10"
output:
  pdf_document: default
  word_document: default
---

```{r setup, echo=FALSE}
# :::::: SOME GLOBAL DEFINITIONS ::::::::

# packages to load
library(Hmisc)
library(stargazer)
library(stats)
library(car)
library(lmtest)

# objects to use in the project
setwd("~/Desktop/Columbia/GR5015/independent_project")
d = read.csv("nba.csv")

#summary <- summary(d)
# visualize the results
stargazer(d, type = "text")
```


```{r normality test}
# conduct the test of normality
shapiro.test(d$Salary)
```

```{r new nor test}
# conduct the test of normality
d$ln.Salary = log(d$Salary)
shapiro.test(d$ln.Salary)
```



```{r initial model}
# :::::: MODEL1 PROCESSING ::::::::

# visualize model1 result
d$ln.Salary = log(d$Salary)
model1 <- lm(ln.Salary ~ Age + G + GS + MP + FG + FGpct + threeP + threePpct + twoP + twoPpct + eFGpct + FT +FTpct+ORB+DRB+AST+STL+BLK+TOV+Pfoul+PTSperG+PG+PF+SG+SF+Exp, data = d)
summary(model1)
```

```{r collinearity}
# check collinearity
vif(model1)
# :::::: descriptions ::::::
# The R function vif () [car package] can be used to detect multicollinearity in a regression model
```


```{r model 2}
# :::::: MODEL2 PROCESSING ::::::::
# visualize model2 result
model2 <- lm(ln.Salary ~ Age + G + GS + threePpct + twoPpct + eFGpct + FTpct + ORB + DRB + AST + STL + BLK + TOV + Pfoul + PG + PF + SG + SF + Exp, data = d)
summary(model2)
```


```{r VIF 2}
# check collinearity
vif(model2)
# :::::: descriptions ::::::
# The R function vif () [car package] can be used to detect multicollinearity in a regression model
```


```{r bp}
# check heteroscedasticity
bptest(model2)
# :::::: descriptions ::::::
# The R function bptest() performs the Breusch-Pagan test against heteroskedasticity
```

```{r plot}
# visualize model2
plot(model2)
```

```{r try}
salarybc <- BoxCoxTrans(d$ln.Salary)
print(salarybc)
```

```{r try 1}
# :::::: MODEL3 PROCESSING ::::::::
# visualize model3 result
d <- cbind(d, salary_new=predict(salarybc, d$ln.Salary))
model3 <-lm(salary_new ~ Age + G + GS + threePpct + twoPpct + eFGpct + FTpct + ORB + DRB + AST + STL + BLK + TOV + Pfoul + PG + PF + SG + SF + Exp, data=d)
summary(model3)
```

```{r 434}
# check heteroscedasticity
bptest(model3)
# :::::: descriptions ::::::
# The R function bptest() performs the Breusch-Pagan test against heteroskedasticity
```

```{r 23}
# visualize model3
plot(model3)
```

```{r 234}
# check collinearity
vif(model3)
# :::::: descriptions ::::::
# The R function vif () [car package] can be used to detect multicollinearity in a regression model
```

```{r 235}
# :::::: MODEL4 PROCESSING ::::::::
# visualize model4 result
model4 <-lm(salary_new ~ Age + G + GS + threePpct:eFGpct:twoPpct + FTpct + ORB + DRB + AST + STL + BLK + TOV + Pfoul + PG + PF + SG + SF + Exp, data = d)
summary(model4)
```

$[ln(Salary)^2 - 1]/ 2 = 85.070 + 0.048*Age + 0.136*G + 0.035*GS + 3.174*FTpct+0.377*ORB+1.301*DRB+2.737*AST+3.781*STL+5.126*BLK+3.689*TOV-1.423*Pfoul-11.080*PG-3.910*PF-3.167*SG+1.147*SF+1.457*Exp-1.042*threePpct*twoPpct*twoPpct$


```{r 457}
# check collinearity
vif(model4)
# :::::: descriptions ::::::
# The R function vif () [car package] can be used to detect multicollinearity in a regression model
```

```{r 09}
# visualize model4
plot(model4)
```
